language: go

sudo: false

os:
  - linux

go:
  - 1.5
  - 1.6

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

install:
 - go get ./...
 - go get -u golang.org/x/lint/golint
 - go get -u golang.org/x/tools/cmd/goimports

script:
 - go vet .
 - diff <(goimports -d .) <(printf "")
 - diff <(golint .) <(printf "")
 - "$HOME/gopath/bin/goveralls -service=travis-ci -v"
env:
  global:
  - secure: Y6o8xA/B/U+zRNuXuMcuteAD16Amh/lHi5/lfTELeuXp3TIR6Enhb16kFglc+vMjCjoKxZWr2nOh2DQ+mQbMjfN4NvAk9Mz54fXq70o12xfEmwivjpfGIymQ4VIVM/mpHrnvPi/oF55nFal5JP/PGrxv2ecl7dJDTelWJGvAUIULzphYVunbDE1WnI2iMMTxURQvsQ+lDXd/K1Qu/IBCESRZHGvUCDFPcpxqpOMa+iblnN5x07GK5SU3QaGP64hObx/ha2nqifvxyUizNZR+s/QBZ2DAI5MjfbTaMf5FThnlQj/T1xNQgGY9rBkAdX3FjyAJRhKjiQ1VwhqKmy7te2OFkulbrHlqgUvTyEFsHz1rRFAROzrvMyQckkktwVMu1YWQIVnmmm7XjznjYIS2jE2SE+bEOD4bHQxiEBFMyluDcOsGHSJSxgXvBmvPniDppRwANB1ASGmoCLkJBZjznpzr1qUsQH6DPbOXQEDR1QCbEfVwOIfGiTVdBkv9L2vm2My30NYhHcjQFIU+35LtE5+/wlpy8S9Vu/rzB5VSobi3Wv1ItKeevhPXk+6e4Z2vqRJoZg+NZQegWZFmQ2d0Q3qH/Xes0KrzUx5MF0dvW0hZRVWyZ+LVQDWj2zNrQdacCOOVMBD7FLm3Uwp/IVJ/Adf3ImzUd9Jsup7+mJwkMlk=
